openapi: 3.0.3
info:
  title: Mastercard Id Assist API
  description: ID Assist provides the technology platform and operational service to allow the secure storage and transmission of Digital Identity data from the user to the Relying Party. The data is verified to a required level of assurance by an Identity Verification Provider.
  contact:
    name: API Support
    email: apisupport@mastercard.com
    url: https://developer.mastercard.com/support
  version: '1.1'
servers:
  - url: 'https://api.mastercard.com/mcidassist'
    description: Production server (uses live data)
  - url: 'https://sandbox.api.mastercard.com/mcidassist'
    description: Sandbox server (testing environment)
tags:
  - name: User
    description: User identification and verification.
  - name: OTP
    description: One Time Passcode (OTP) generation and verification for SMS.
  - name: Device Authentication
    description: Authenticate a mobile device using the IP address and verifying by passing a fingerprint for the device.
paths:
  /device-authentications:
    post:
      x-mastercard-api-encrypted: true
      tags:
        - Device Authentication
      responses:
        '200':
          $ref: '#/components/responses/DeviceAuthenticationSuccess'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
      description: This API provides a ``redirectTargetUrl`` for a given device IP Address. The ``redirectTargetUrl`` can be used to retrieve a ``verificationFingerprint`` which is used for verification in ``/device-authentication-verifications``
      operationId: Device Authentication
      summary: Device Authentication
      requestBody:
        $ref: '#/components/requestBodies/DeviceAuthenticationRequestBody'
  /sms-otps:
    post:
      x-mastercard-api-encrypted: true
      tags:
        - OTP
      responses:
        '200':
          $ref: '#/components/responses/SMSOTPSuccess'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
      description: Create and Send a One-Time Passcode (OTP) via SMS to the phone number provided.
      operationId: Create otps - SMS
      summary: Generate an SMS OTP
      requestBody:
        $ref: '#/components/requestBodies/SMSOTPGenerationRequestBody'
  /device-authentication-verifications:
    post:
      x-mastercard-api-encrypted: true
      tags:
        - Device Authentication
      responses:
        '200':
          $ref: '#/components/responses/DeviceAuthenticationVerificationsSuccess'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
      description: Use this API to retrieve a phone number for a device ``verificationFingerprint``. The ``verificationFingerprint`` is retrieved by calling the ``redirectTargetUrl`` returned from ``/device-authentications``
      operationId: Device Authentication Verification
      summary: Device Authentication Verification
      requestBody:
        $ref: '#/components/requestBodies/DeviceVerificationFingerprintRequestBody'
  /user-verifications:
    post:
      x-mastercard-api-encrypted: true
      tags:
        - User
      responses:
        '200':
          $ref: '#/components/responses/UserVerificationsSuccess'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      description: Verifies user entered Personally Identifiable Information (PII) by returning a true/false or matching score per attribute along with an overall trust score for the record
      operationId: Identity Verification API
      summary: Verify an Identity
      requestBody:
        $ref: '#/components/requestBodies/IdentityVerificationUserInfoRequestBody'
  /user-identities:
    post:
      x-mastercard-api-encrypted: true
      tags:
        - User
      responses:
        '200':
          $ref: '#/components/responses/UserIdentitiesSuccess'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      description: |-
        This API will provide information about an individual user with one of the following:
        - Phone Number and Last 4 Digits of SSN
        - Phone Number and National ID
        - Phone Number and Date of Birth
      operationId: Identity API
      summary: Retrieve an Identity
      requestBody:
        $ref: '#/components/requestBodies/IdentityPrefillRequestBody'
  /trust-score:
    post:
      x-mastercard-api-encrypted: true
      tags:
        - User
      responses:
        '200':
          $ref: '#/components/responses/TrustScoreSuccess'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      description: This API will provide trust information about an individual user
      operationId: Trust API
      summary: Retrieve trust for an identity
      requestBody:
        $ref: '#/components/requestBodies/TrustScoreUserInfoRequestBody'
  /sms-otp-verifications:
    post:
      x-mastercard-api-encrypted: true
      tags:
        - OTP
      responses:
        '200':
          $ref: '#/components/responses/SMSOTPVerificationsSuccess'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
      description: Verify that the provided code matches One-Time Passcode (OTP) sent via SMS during `/sms-otps`
      operationId: Verify otps
      summary: Verify an SMS OTP
      requestBody:
        $ref: '#/components/requestBodies/SMSOTPVerificationRequestBody'
components:
  schemas:
    SMSOTPVerificationResult:
      required:
        - transactionId
      type: object
      properties:
        transactionId:
          type: string
          example: 7f83-b0c4-90e0-90b3-11e10800200c9a66
          pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
          description: A random 128-bit. UUID representing the MIDS transaction
        responseCode:
          type: string
          example: FAILURE
          description: The result of the OTP verification. It can be either ``SUCCESS``, ``FAILURE`` or ``ATTEMPTS_EXCEEDED``
          minLength: 7
          maxLength: 17
        responseMessage:
          type: string
          example: Incorrect code provided
          description: A short message describing the response code
          minLength: 1
          maxLength: 255
        attemptsRemaining:
          type: integer
          format: int32
          example: 2
          description: The number of attempts remaining. This field is only populated for the ``FAILURE`` response code
    IdentityPrefill:
      required:
        - countryCode
        - optedInConsentStatus
        - phoneNumber
        - scopedFields
      type: object
      properties:
        phoneNumber:
          type: string
          pattern: '^[1-9]\d{1,14}$'
          example: 13143039289
          description: 'The phone number being queried in standard international format. It should be prefixed with the international dialling code, without the ''+''.'
        dob:
          type: string
          example: '1984-01-15'
          pattern: '^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$'
          description: date of birth
        last4ssn:
          type: string
          example: 1234
          pattern: '^[0-9]{4}$'
          description: The User's last four social security number digits. One of either dob or last4ssn is required. If the countryCode is US then, last4ssn or nationalId is required.
        nationalId:
          type: string
          example: 123456789
          description: The national identification number. If the countryCode is US then, last4ssn or nationalId is required.
            If both nationalId and last4ssn are present then, use only the nationalId.
            If the countryCode is US then this field must be a numeric value that is 9 digits long.
          minLength: 2
          maxLength: 50
        countryCode:
          type: string
          example: US
          pattern: '^[a-zA-Z]{2}$'
          description: ISO-3166 Alpha-2 standard.
        scopedFields:
          minItems: 1
          type: array
          example:
            - firstName
            - lastName
            - emailAddress
          items:
            type: string
          description: The fields to be scoped.  At least one field in the array should be present.
        optedInConsentStatus:
          type: boolean
          example: true
          description: 'Should be true, validation exception will be thrown if it is false.'
        performEligibilityCheck:
          type: boolean
          default: true
          example: true
          description: If false will not perform an eligibility check
    TrustScoreUserInfo:
      required:
        - countryCode
        - optedInConsentStatus
        - phoneNumber
      type: object
      properties:
        phoneNumber:
          type: string
          pattern: '^[1-9]\d{1,14}$'
          example: 13143039289
          description: 'The phone number being queried in standard international format. It should be prefixed with the international dialling code, without the ''+''.'
        countryCode:
          type: string
          example: US
          pattern: '^[a-zA-Z]{2}$'
          description: ISO-3166 Alpha-2 standard.
        optedInConsentStatus:
          type: boolean
          example: true
          description: 'Should be true, validation exception will be thrown if it is false.'
        performEligibilityCheck:
          type: boolean
          default: false
          example: true
          description: Default false.  If true will perform an eligibility check
    IdentityVerificationUserInfo:
      required:
        - countryCode
        - optedInConsentStatus
        - phoneNumber
      type: object
      properties:
        optedInConsentStatus:
          type: boolean
          example: true
          description: 'Should be true, validation exception will be thrown if it is false.'
        phoneNumber:
          type: string
          example: 13143039289
          pattern: '^[1-9]\d{1,14}$'
          description: 'The phone number being queried in standard international format. It should be prefixed with the international dialling code, without the ''+''.'
        firstName:
          type: string
          example: John
          pattern: '^[a-zA-Z\d ,.''‘’-]{1,50}$'
          description: The user's first name
        lastName:
          type: string
          example: Doe
          pattern: '^[a-zA-Z\d ,.''‘’-]{1,50}$'
          description: The user's last name
        countryCode:
          type: string
          example: US
          pattern: '^[a-zA-Z]{2}$'
          description: ISO-3166 Alpha-2 standard.
        address:
          type: string
          example: 123 Main St
          pattern: '^[a-zA-Z\d ,.''‘’-]{1,50}$'
          description: The user's address
        extendedAddress:
          type: string
          example: Apt. 202
          pattern: '^[a-zA-Z\d ,.''‘’-]{1,50}$'
          description: The user's address complement
        city:
          type: string
          example: San Francisco
          pattern: '^[a-zA-Z ,.''‘’-]{1,50}$'
          description: The user's city
        region:
          type: string
          example: CA
          pattern: '^[a-zA-Z]{2}$'
          description: The user's region
        postalCode:
          type: string
          example: 94015
          pattern: '^[a-zA-Z\d ,.''-]{1,50}$'
          description: If address matching is desired at a minimum ``postalCode`` is required
        dob:
          type: string
          example: '1984-01-15'
          pattern: '^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$'
          description: The user's date of birth format YYYY-MM-DD. One of either dob or last4ssn is required.
        last4ssn:
          type: string
          example: 1234
          pattern: '^\d{4}$'
          description: The User's last four social security number digits. One of either dob or last4ssn is required. If the countryCode is US then, last4ssn or nationalId is required.
        nationalId:
          minLength: 2
          maxLength: 50
          type: string
          example: 123456789
          description: The national identification number. If the countryCode is US then, last4ssn or nationalId is required. If both nationalId and last4ssn are present then, use only the nationalId.
        emailAddress:
          type: string
          pattern: '^[\w\.\''\‘\’-]+@([\w-]+\.)+[\w-]{2,4}$'
          example: abc@def.com
          description: The user's email address
    SMSOTP:
      required:
        - otpId
        - transactionId
      type: object
      properties:
        transactionId:
          type: string
          example: 7f83-b0c4-90e0-90b3-11e10800200c9a66
          pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
          description: A random 128-bit. UUID representing the MIDS transaction
        otpId:
          type: string
          example: 4b24557f-50a2-4e01-898b-ab8575527cac
          pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
          description: Passed into `/sms-otp-verifications` along with code received by sms
    Identity:
      required:
        - scopedFields
        - transactionId
      type: object
      description: The fields to be scoped
      properties:
        transactionId:
          type: string
          example: 7f83-b0c4-90e0-90b3-11e10800200c9a66
          description: A random 128-bit. UUID representing the MIDS transaction
          pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
        scopedFields:
          type: object
          properties:
            firstName:
              type: string
              example: John
              description: The user's first name
              pattern: '^[a-zA-Z\d ,.''‘’-]{1,50}$'
            lastName:
              type: string
              example: Doe
              description: The user's last name
              pattern: '^[a-zA-Z\d ,.''‘’-]{1,50}$'
            dob:
              type: string
              example: '19810627'
              description: The user's date of birth (YYYYMMDD)
              pattern: '^([12]\d{3}(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01]))$'
            nationalId:
              type: string
              example: 123456789
              description: The national identification number
              minLength: 2
              maxLength: 50
            address:
              type: object
              properties:
                address:
                  type: string
                  example: 123 Main St
                  description: The user's address description
                  pattern: '^[a-zA-Z\d ,.''‘’-]{1,50}$'
                extendedAddress:
                  type: string
                  example: Apt. 202
                  description: The user's extended address
                  pattern: '^[a-zA-Z\d ,.''‘’-]{1,50}$'
                city:
                  type: string
                  example: San Francisco
                  description: The user's city
                  pattern: '^[a-zA-Z ,.''‘’-]{1,50}$'
                region:
                  type: string
                  example: CA
                  description: The user's region
                  pattern: '^[a-zA-Z]{2}$'
                postalCode:
                  type: string
                  example: 94015
                  description: The user's postal code
                  pattern: '^[a-zA-Z\d ,.''-]{1,50}$'
              description: The user's address
            emailAddress:
              type: string
              example: abc@def.com
              description: The user's email address
              pattern: '^[\w\.\''\‘\’-]+@([\w-]+\.)+[\w-]{2,4}$'
    TrustScore:
      required:
        - transactionId
        - phoneNumber
        - trustScore
      type: object
      properties:
        transactionId:
          type: string
          example: 7f83-b0c4-90e0-90b3-11e10800200c9a66
          description: A random 128-bit. UUID representing the MIDS transaction
          pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
        lineType:
          type: string
          example: 'landline'
          description: 'A string value that denotes the line characteristics of the phone number. Possible values: ''landline'', ''mobile'', ''fixedVoIP'', ''nonFixedVoIP'', ''other'''
          minLength: 5
          maxLength: 12
        trustScore:
          type: integer
          example: 1000
          description: An integer value ranging from 0 - 1000 that denotes the real-time trustworthiness of a phone number. 1000 indicates perfect trust while 0 indicates a complete lack of trust.
        reasonCodes:
          type: array
          example:
            - LP
            - LS
          description: |
            An array of indicators that provide additional context about the Transaction. For complete list.
            |   Reason Code |   Description |
            |:--------------|:------------------|
            |AC|Normalized address was used to complete empty address fields prior to match.|
            |AU|Address Undeliverable.|
            |BA|Business Address.|
            |BL|Mobile Business Line.|
            |CN|First and Last name combined in one field.|
            |DA|Dual address (Ex. 123 Main St PO Box 99).|
            |DI|Death Indicator found on data.|
            |DT|Data retrieval timeout (verify API only).|
            |DV|High device change velocity.|
            |FN|Family name found and used in matching.|
            |GL|Mobile Government Line.|
            |HR|High-rise; address contains apartment or building sub-units.|
            |HV|High velocity of change events associated with phone.|
            |IA|Inactive address.|
            |LA|Low Tenure Address.|
            |LP|Low Tenure Device.|
            |LS|Low Tenure SIM.|
            |LT|Low Tenure Mobile Identity.|
            |MA|Address in the request associated with multiple active addresses.|
            |MI|Military address.|
            |NA|Address is valid and has been normalized prior to calculating the match score.|
            |NC|Name & Address information is not available.|
            |ND|Network Status information is not available.|
            |NM|Not a mobile line type.|
            |NN|Nick name found and used in matching. For example Bill matches with William.|
            |NP|Non personal line.|
            |NS|Names were swapped (first/last).|
            |NU|Phone number has been updated.|
            |NV|Phone number not valid.|
            |OL|How long the identity has been associated to a phone number. Long Tenure > 90 days.|
            |OS|How long the identity has been associated to a phone number. Short Tenure between 8 and 90 days.|
            |OU|The date attributes associated to the phone number is not available. Ownership Tenure is Unknown.|
            |OV|How long the identity has been associated to a phone number. Very Short < 7 days.|
            |P3|Postal code submitted matched first 3 digits.|
            |P5|Postal code submitted matched first 5 digits.|
            |P9|Postal code submitted matched first 9 digits.|
            |PM|Address associated with a Private Mailbox operator (Ex. UPS Store).|
            |PN|Mobile Phone number is not active.|
            |PO|Address is a PO Box.|
            |PT|Phone Number is currently in a ported state.|
            |RA|Raw Address matched better than normalized Address.|
            |RL|Phone Number is associated with a high-risk linetype (Non-Fixed `VoIP` or Prepaid `MVNO`).|
            |RM|Matching used only Raw data.|
            |SA|Sub-account line.|
            |UC|Insufficient data to calculate trustScore.|
            |UV|Unable to verify address.|
            |VA|Address is vacant (unoccupied in the past 90 days).|
            More details see [link](http://docs.payfone.com/v1.0/reference#reason-codes)
          items:
            type: string
            example: AC
        eligibility:
          type: boolean
          example: true
          description: A flag indicating eligibility.
    Error:
      required:
        - Errors
      type: object
      properties:
        Errors:
          required:
            - Error
          type: object
          properties:
            Error:
              minItems: 1
              type: array
              items:
                type: object
                properties:
                  Source:
                    type: string
                    example: DI
                  ReasonCode:
                    type: string
                    example: REASON_CODE
                  Description:
                    type: string
                    example: Description of the error
                  Recoverable:
                    type: boolean
                    example: true
                  Details:
                    type: string
                    example: Specifics as to why there was an error
                description: a list of Error objects
    IdentityVerification:
      type: object
      properties:
        transactionId:
          type: string
          example: 7f83-b0c4-90e0-90b3-11e10800200c9a66
          description: A random 128-bit. UUID representing the MIDS transaction
          pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
        name:
          type: object
          properties:
            firstName:
              type: integer
              format: int32
              example: 100
              description: The user's first name
              minLength: 1
              maxLength: 3
            lastName:
              type: integer
              format: int32
              example: 100
              description: The user's last name
              minLength: 1
              maxLength: 3
            nameScore:
              type: integer
              format: int32
              example: 100
              description: The user's name score
              minLength: 1
              maxLength: 3
        address:
          type: object
          properties:
            streetNumber:
              type: integer
              format: int32
              example: 100
              description: The user's street number
              minLength: 1
              maxLength: 3
            street:
              type: boolean
              example: true
              description: Response from identity verification provider
            city:
              type: boolean
              example: true
              description: Response from identity verification provider
            region:
              type: boolean
              example: true
              description: Response from identity verification provider
            postalCode:
              type: boolean
              example: true
              description: Response from identity verification provider
            addressScore:
              type: integer
              format: int32
              example: 100
              description: The user's address score
          description: The user's address
        identifiers:
          type: object
          properties:
            last4ssn:
              type: boolean
              example: true
              description: Response from identity verification provider
            nationalId:
              type: boolean
              example: true
              description: Response from identity verification provider
            dob:
              type: boolean
              example: true
              description: Response from identity verification provider
        email:
          type: object
          properties:
            emailAddress:
              type: boolean
              example: true
              description: Response from identity verification provider
        trustScore:
          type: integer
          format: int32
          example: 1000
          description: The user's trust score
        phoneNumber:
          type: string
          example: 13143039289
          description: The user's phone number
          pattern: '^[1-9]\d{1,14}$'
        reasonCodes:
          minItems: 0
          type: array
          example:
            - LP
            - LS
          items:
            type: string
            example: AC
          description: |
            An array of indicators that provide additional context about the Transaction. For complete list.
            |   Reason Code |   Description |
            |:--------------|:------------------|
            |AC|Normalized address was used to complete empty address fields prior to match.|
            |AU|Address Undeliverable.|
            |BA|Business Address.|
            |BL|Mobile Business Line.|
            |CN|First and Last name combined in one field.|
            |DA|Dual address (Ex. 123 Main St PO Box 99).|
            |DI|Death Indicator found on data.|
            |DT|Data retrieval timeout (verify API only).|
            |DV|High device change velocity.|
            |FN|Family name found and used in matching.|
            |GL|Mobile Government Line.|
            |HR|High-rise; address contains apartment or building sub-units.|
            |HV|High velocity of change events associated with phone.|
            |IA|Inactive address.|
            |LA|Low Tenure Address.|
            |LP|Low Tenure Device.|
            |LS|Low Tenure SIM.|
            |LT|Low Tenure Mobile Identity.|
            |MA|Address in the request associated with multiple active addresses.|
            |MI|Military address.|
            |NA|Address is valid and has been normalized prior to calculating the match score.|
            |NC|Name & Address information is not available.|
            |ND|Network Status information is not available.|
            |NM|Not a mobile line type.|
            |NN|Nick name found and used in matching. For example Bill matches with William.|
            |NP|Non personal line.|
            |NS|Names were swapped (first/last).|
            |NU|Phone number has been updated.|
            |NV|Phone number not valid.|
            |OL|How long the identity has been associated to a phone number. Long Tenure > 90 days.|
            |OS|How long the identity has been associated to a phone number. Short Tenure between 8 and 90 days.|
            |OU|The date attributes associated to the phone number is not available. Ownership Tenure is Unknown.|
            |OV|How long the identity has been associated to a phone number. Very Short < 7 days.|
            |P3|Postal code submitted matched first 3 digits.|
            |P5|Postal code submitted matched first 5 digits.|
            |P9|Postal code submitted matched first 9 digits.|
            |PM|Address associated with a Private Mailbox operator (Ex. UPS Store).|
            |PN|Mobile Phone number is not active.|
            |PO|Address is a PO Box.|
            |PT|Phone Number is currently in a ported state.|
            |RA|Raw Address matched better than normalized Address.|
            |RL|Phone Number is associated with a high-risk linetype (Non-Fixed `VoIP` or Prepaid `MVNO`).|
            |RM|Matching used only Raw data.|
            |SA|Sub-account line.|
            |UC|Insufficient data to calculate trustScore.|
            |UV|Unable to verify address.|
            |VA|Address is vacant (unoccupied in the past 90 days).|
            More details see [link](http://docs.payfone.com/v1.0/reference#reason-codes)
        verified:
          type: boolean
          example: true
          description: Whether a user identity is verified
        lineType:
          type: string
          example: Mobile
          description: The line type. It can be either ``Mobile``, ``Landline``, ``FixedVoIP`` or ``NonFixedVoIP``
          minLength: 5
          maxLength: 12
    SMSOTPVerification:
      required:
        - code
        - countryCode
        - optedInConsentStatus
        - otpId
      type: object
      properties:
        otpId:
          type: string
          example: 4b24557f-50a2-4e01-898b-ab8575527cac
          pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
          description: Returned from `/sms-otps`
        code:
          type: string
          example: 123456
          pattern: '^[0-9]{6}$'
          description: This is the code received by sms after calling `/sms-otps`
        countryCode:
          type: string
          example: US
          pattern: '^[a-zA-Z]{2}$'
          description: ISO-3166 Alpha-2 standard.
        optedInConsentStatus:
          type: boolean
          example: true
          description: 'Should be true, validation exception will be thrown if it is false.'
    DevicePhoneNumber:
      required:
        - phoneNumber
        - transactionId
      type: object
      properties:
        transactionId:
          type: string
          example: 7f83-b0c4-90e0-90b3-11e10800200c9a66
          description: A random 128-bit. UUID representing the MIDS transaction
          pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
        phoneNumber:
          type: string
          example: 13143039289
          description: 'The phone number of the originating phone, prefixed with the international dialling code, without the ``+``.'
          pattern: '^[1-9]\d{1,14}$'
    DeviceVerificationFingerprint:
      required:
        - countryCode
        - optedInConsentStatus
        - verificationFingerprint
      type: object
      properties:
        verificationFingerprint:
          type: string
          example: 4f544a6a596a4d304d3249745a4752684f5330304d3249794c5745324e7a41744d44646d5a5459314d57526a593245306644413d3a4e5af1cf7e052335e57a51f3e0b1362fa58d4c220d9adef9179895b4c4beda59
          pattern: '^[a-zA-Z0-9]{128,2096}$'
          description: Retrieved by calling the `redirectTargetUrl` returned from `/device-authentications`.
        countryCode:
          type: string
          example: US
          pattern: '^[a-zA-Z]{2}$'
          description: ISO-3166 Alpha-2 standard.
        optedInConsentStatus:
          type: boolean
          example: true
          description: 'Should be true, validation exception will be thrown if it is false.'
    SMSOTPGeneration:
      required:
        - countryCode
        - optedInConsentStatus
        - phoneNumber
      type: object
      properties:
        phoneNumber:
          type: string
          example: 13143039289
          pattern: '^[1-9]\d{1,14}$'
          description: 'The phone number being queried in standard international format. It should be prefixed with the international dialling code, without the ''+''.'
        countryCode:
          type: string
          example: US
          pattern: '^[a-zA-Z]{2}$'
          description: ISO-3166 Alpha-2 standard.
        optedInConsentStatus:
          type: boolean
          example: true
          description: 'Should be true, validation exception will be thrown if it is false.'
        locale:
          type: string
          example: en-GB
          pattern: '^[a-z]{2}-[a-zA-Z]{2}$'
          description: 'Follows the IETF BCP 47 Format E.g. "en-GB" (English - United Kingdom), "es-MX" (Spanish - Mexico).'
    DeviceIpAddress:
      required:
        - countryCode
        - deviceIp
        - optedInConsentStatus
      type: object
      properties:
        countryCode:
          type: string
          pattern: '^[a-zA-Z]{2}$'
          example: US
          description: ISO-3166 Alpha-2 standard.
        optedInConsentStatus:
          type: boolean
          example: true
          description: 'Should be true, validation exception will be thrown if it is false.'
        deviceIp:
          maxLength: 45
          type: string
          example: 166.137.217.20
          pattern: '^([a-fA-F0-9:]+|(\d{1,3}\.){3}\d{1,3})$'
          description: Both IPv4 and IPv6 are supported.
    DeviceAuthenticationVerificationUrl:
      required:
        - redirectTargetUrl
        - transactionId
      type: object
      properties:
        transactionId:
          type: string
          example: 7f83-b0c4-90e0-90b3-11e10800200c9a66
          description: A random 128-bit. UUID representing the MIDS transaction
          pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
        redirectTargetUrl:
          type: string
          example: 'http://device.staging.payfone.com/mobileauth/2014/07/01/deviceAuthenticate?vfp=4e6a63354d4745'
          pattern: 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&\/=]*)'
          description: Use this url to retrieve the `verificationFingerprint` which is passed into `/device-authentication-verifications`.
  responses:
    NotFoundError:
      description: Request didn't match an existing resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            NotFoundExample:
              $ref: '#/components/examples/NotFoundExample'
    BadRequestError:
      description: Something was wrong with the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            BadRequestExample:
              $ref: '#/components/examples/BadRequestExample'
            TooManyOtpRequestsExample:
              $ref: '#/components/examples/TooManyOtpRequestsExample'
    UnauthorizedError:
      description: Unauthorized request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            UnauthorizedExample:
              $ref: '#/components/examples/UnauthorizedExample'
    ForbiddenError:
      description: Consent not given.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            ForbiddenExample:
              $ref: '#/components/examples/ForbiddenExample'
    DeviceAuthenticationSuccess:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeviceAuthenticationVerificationUrl'
    SMSOTPSuccess:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SMSOTP'
    DeviceAuthenticationVerificationsSuccess:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DevicePhoneNumber'
    UserVerificationsSuccess:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/IdentityVerification'
    UserIdentitiesSuccess:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Identity'
    TrustScoreSuccess:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TrustScore'
    SMSOTPVerificationsSuccess:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SMSOTPVerificationResult'
  requestBodies:
    DeviceAuthenticationRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeviceIpAddress'
      required: true
    SMSOTPGenerationRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SMSOTPGeneration'
      required: true
    DeviceVerificationFingerprintRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeviceVerificationFingerprint'
      required: true
    IdentityVerificationUserInfoRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/IdentityVerificationUserInfo'
      required: true
    IdentityPrefillRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/IdentityPrefill'
      required: true
    TrustScoreUserInfoRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TrustScoreUserInfo'
      required: true
    SMSOTPVerificationRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SMSOTPVerification'
      required: true
  examples:
    NotFoundExample:
      value:
        Errors:
          Error:
            - Source: mids
              ReasonCode: NOT_ELIGIBLE
              Description: No eligible data found for the specified phoneNumber
              Recoverable: false
    UnauthorizedExample:
      value:
        Errors:
          Error:
            - Source: mids
              ReasonCode: UNAUTHORIZED_REQUEST
              Description: Unauthorized request
              Recoverable: false
    ForbiddenExample:
      value:
        Errors:
          Error:
            - Source: mids
              ReasonCode: CONSENT NOT GIVEN
              Description: Consent must be given
              Recoverable: false
    BadRequestExample:
      value:
        Errors:
          Error:
            - Source: mids
              ReasonCode: INVALID_FIELD_VALUE
              Description: 'Invalid ''phoneNumber'': must match "^[1-9]\d{1,14}$"'
              Recoverable: false
              Details:
                - Name: field
                  Value: phoneNumber
                - Name: validationError
                  Value: 'must match "^[1-9]\d{1,14}$"'
    TooManyOtpRequestsExample:
      value:
        Errors:
          Error:
            - Source: mids
              ReasonCode: TOO_MANY_OTP_REQUESTS
              Description: 'TOO_MANY_OTP_REQUESTS: Requestor sent more than one OTP generation request within the cooldown time of 60 seconds'
              Recoverable: true